[build]
builder = "nixpacks"
buildCommand = """
cd backend
pip install --upgrade pip
pip install -r requirements.txt
"""
builderImage = "python:3.9"

[deploy]
startCommand = "cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[variables]
PYTHONPATH = "/app/backend"
NIXPACKS_PYTHON_VERSION = "3.9"
NIXPACKS_INSTALL_CMD = "pip install -r requirements.txt"
NIXPACKS_BUILD_CMD = "echo 'No build step needed'"