"""update interaction model fields

Revision ID: 44f6be3f44d9
Revises: 7cc8096371ad
Create Date: 2025-04-24 13:25:54.086536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44f6be3f44d9'
down_revision: Union[str, None] = '7cc8096371ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interactions', sa.Column('subject', sa.String(), nullable=False))
    op.add_column('interactions', sa.Column('description', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interactions', 'description')
    op.drop_column('interactions', 'subject')
    # ### end Alembic commands ###
