"""add_closed_date_to_opportunities

Revision ID: 477f5e9ea3cb
Revises: 44f6be3f44d9
Create Date: 2025-05-01 15:23:46.819728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '477f5e9ea3cb'
down_revision: Union[str, None] = '44f6be3f44d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opportunities', sa.Column('closed_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('opportunities', 'closed_date')
    # ### end Alembic commands ###
