"""add invitation token

Revision ID: ca8721b908c5
Revises: fceacf5f5231
Create Date: 2025-04-03 14:36:51.545687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca8721b908c5'
down_revision: Union[str, None] = 'fceacf5f5231'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('invitation_token', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'users', ['invitation_token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'invitation_token')
    # ### end Alembic commands ###
